### ISSUE TITLE
"Error while starting streaming server" with external players

### ISSUE THREAD

**Issue by Kabouik** [Stremio/stremio-core#103]
When I try to stream a video from a torrent file in mpv as external player (right click in the Stremio builtin player, play in mpv), I get the following error:

```
Error while starting streaming server. Please consider re-installing Stremio from 
Stremio streaming server has thrown an error from https://www.stremio.com

QProcess::ProcessError code: 1

(node:9783) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
fs.js:127
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1248:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:132655:36)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
```
Please note that streaming does work in the builtin Stremio player. It also works *sometimes* in mpv, but the mpv window may eventually close with no error, and then the message will appear every time I try to play the movie in mpv again, even after restarting Stremio (while the builtin player will still work). This pattern with mpv first working temporarily and then failing all the time made me think maybe the issue was related to the cache, but deleting the content of the cache folder right after getting the issue and restarting Stremio did not solve the issue, the error pop-up appeared immediately when trying to play in mpv again. 

I get the exact same error when trying to play in vlc as external player, so the issue is probably not with the player itself.

Any ideas?

### Versions
Stremio 4.4.77 installed from AUR.
Web UI 4.4.95
Server 4.6.0
Using mpv as external player

**Comment by Ivshti** [comment]
I'm going to move this issue to stremio-shell

otherwise, this looks like stremio is started with the wrong working directory

try startng it from a directory you can write in (e.g. `$HOME`) 

another thing you can tyr is disable the cache (set it to "No cache")
