### ISSUE TITLE
Error while starting streaming server - play with VLC

### ISSUE THREAD

**Issue by wonbinbk** [Stremio/stremio-core#233]
Hi, I intermittently got this issue when I tried to play video with VLC. The error was as below:

> Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:149373) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:320
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:495:3)
    at Object.writeFileSync (node:fs:1519:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:129896:36)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
(node:195486) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:320
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:495:3)
    at Object.writeFileSync (node:fs:1519:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:129896:36)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
(node:217427) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:320
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:495:3)
    at Object.writeFileSync (node:fs:1519:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:129896:36)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
(node:237971) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:320
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:495:3)
    at Object.writeFileSync (node:fs:1519:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:129896:36)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
(node:238168) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:320
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:495:3)
    at Object.writeFileSync (node:fs:1519:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:129896:36)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}

**Comment by Ivshti** [comment]
this is the wrong repo for the issue (right one is stremio-shell) but we'll investigate it anyway

cc @nklhrstv  and @TRtomasz
