### ISSUE TITLE
Arch Linux, stremio not working

### ISSUE THREAD

**Issue by Harith163** [Stremio/stremio-core#294]
I get the following error when launching stremio. Have uninstalled and reinstalled several times to no effect. 

Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:1813) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
(node:1948) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0

**Comment by tahsinrahman** [comment]
same here. tried installing stremio-beta, still same issue

**Comment by hajking** [comment]
[fix](https://www.reddit.com/r/Stremio/comments/uic760/error_while_starting_streaming_server_please/)

**Comment by hajking** [comment]
here is the command

sudo sed -i 's/details.family.toLowerCase()/details.family.toString().toLowerCase()/g' /opt/stremio/server.js

**Comment by Harith163** [comment]
That worked! Thank you. Hopefully this change gets incorporated properly
