### ISSUE TITLE
Error starting streaming server

### ISSUE THREAD

**Issue by fjwillemsen** [Stremio/stremio-core#428]
Hope this is the right repository to post this issue! 
On macOS (13.2, latest stable) I have a problem where the streaming server crashes when trying to open a stream from the web client at https://[my-ip].[id].stremio.rocks:12470, even on the same device. 

The error dialog says the following: "Error while starting streaming server. Please consider re-installing Stremio from https://www.stremio.com", and gives the following details:
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:15812) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Applications/Stremio.app/Contents/MacOS/server.js:134698
	var body = JSON.stringify({ error: error, result: result });
	                ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify (<anonymous>)
    at /Applications/Stremio.app/Contents/MacOS/server.js:134698:18
    at /Applications/Stremio.app/Contents/MacOS/server.js:140778:21
    at /Applications/Stremio.app/Contents/MacOS/server.js:134996:25
    at ClientRequest.<anonymous> (/Applications/Stremio.app/Contents/MacOS/server.js:125558:21)
    at ClientRequest.f (/Applications/Stremio.app/Contents/MacOS/server.js:106244:25)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Initially I used brew to install, but I have already downloaded reinstalled, same error. 
When running Stremio via the terminal, I get the following output: 
```
Using app path -> /Users/***/Library/Application Support/stremio-server
Enabling casting...
Discovery of new external device "vlc" - VLC
(node:16703) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
qml: Auto-updater: up to date
```
So it seems the HTTPS endpoint initiates just fine. But when opening a stream, it gives the same error as above.

**Comment by TRtomasz** [comment]
For bugs reports please use https://github.com/Stremio/stremio-bugs/issues
