### ISSUE TITLE
[Bug] Server not working when I try to play anything

### ISSUE THREAD

**Issue by otDan** [Stremio/stremio-core#612]
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:42040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:36012
                var code = error ? 500 : 200, body = JSON.stringify({
                                                          ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify (<anonymous>)
    at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:36012:59
    at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:27013:52
    at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:59684:29
    at ClientRequest.<anonymous> (C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:27580:25)
    at ClientRequest.f (C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:6431:70)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by TRtomasz** [comment]
For bugs please use stremio-bugs repository, if this is still happening please reopen your ticket there and include minimal details about your setup.
